import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';  
import {Incidencia} from '../models/incidencia'
import {Nivel} from '../models/nivel'

@Component({
  selector: 'app-formci',
  templateUrl: './formci.component.html',
  styleUrls: ['./formci.component.css']
})
export class FormciComponent implements OnInit {
public incidencias : Incidencia[]=[];
public niveles: Nivel[]=[]; 
public nuevaincidencia: Incidencia;
public ramaunicae: string[]=[]
public ramaunicae2 = new Map<String, String>();


  titlex="hola caracola ssssssssssssssssssssssssssssssssss";
  constructor(  ) { }

  ngOnInit(): void {

    this.nuevaincidencia = new Incidencia("","","","","",new Date(),new Date(),"",new Date(),new Date(),"","","","","",new Date(),new Date(),false,new Date(),new Date(),"",0,"","","",false,false,false,false,"",0,false,false,"",false,false,false,false,false,false,"","","","","","","",false,"",0),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','1','Semaforización Tranviaria','1','Alimentación',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','1','Semaforización Tranviaria','2','Piloto de Señalización',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','1','Semaforización Tranviaria','3','Detector Tranvía',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','2','Semaforización Viaria','1','Alimentación',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','2','Semaforización Viaria','2','Piloto de Señalización',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','2','Semaforización Viaria','3','Detector Tranvía',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','3','Motores. Circuitos de Vía','1','Alimentación Motores',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','3','Motores. Circuitos de Vía','2','Motor Eléctrico',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','3','Motores. Circuitos de Vía','3','Detectores de Posición',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','4','Armario Control Agujas','1','Alimentación -Fuente de Alimentación',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','4','Armario Control Agujas','2','Electrónica',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','1','Señalizaciones','4','Armario Control Agujas','3','Contactores, Protec.Etectricas',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','1','SIV','1','Panel',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','1','SIV','2','Alimentación',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','2','Megafonía','1','Altavoz',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','2','Megafonía','2','Equipo de Potencia',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','3','Interfonía','1','Panel Interfonía',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','3','Interfonía','2','Alimentación',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','4','Red','1','Fibra Optica',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','4','Red','2','Switch',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','5','Telefonía','0','NULL',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','6','Radio Tetra','1','Subestaciones',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','6','Radio Tetra','2','Antena',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','2','Comunicaciones','6','Radio Tetra','3','Terminales Móviles',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','1','Catenaria','1','Hilo de Contacto',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','1','Catenaria','2','Poste de Catenaria',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','1','Catenaria','3','Soportes Hilo de Contacto',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','1','Catenaria','4','Seccionadores',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','1','Catenaria','5','Control Seccionadores',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','2','SE','1','Feeders',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','2','SE','2','Transformadores',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','3','Paradas','1','Cuadro Distribución Eléctrica',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','3','Paradas','2','Iluminación',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','3','Energía','3','Paradas','3','SAI',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','1','Impresora',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','2','Aceptadora de Billetes',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','3','Aceptadora de Monedas',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','4','Lector de Bonos',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','5','Tarjeta Bancaria',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','6','Recarga',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','7','Aplicativo',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','8','Daños Fisicos',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','4','Billetaje','1','Expendedora','9','Acceso Remoto',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','5','SAE','1','Balizas','0','NULL',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','6','Otras Instalaciones','1','CCTV','1','Cámara Domo',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','6','Otras Instalaciones','1','CCTV','2','Cámara Fija',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','1','Plataforma','1','Adoquines',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','1','Plataforma','2','Césped',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','1','Plataforma','3','Cemento',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','1','Plataforma','4','Drenaje',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','2','Paradas','1','Bloque técnico',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','2','Paradas','2','Barandillas',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','2','Paradas','3','Decoración',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','2','Paradas','4','Techo',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','2','Paradas','5','Suelo',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','3','Carriles','1','Carril',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','3','Carriles','2','Detectores Ferroviarios',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','3','Carriles','3','Detectores Tranviarios',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','3','Carriles','4','Chaqueta',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','4','Aparatos de Vía','1','Cambio Automático',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','4','Aparatos de Vía','2','Cambio Manual',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','7','Infraestructura y Vía','5','Obra Civil','1','Bordillo',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','1','Vehículo 151',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','10','Vehículo 163',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','11','Vehículo 164',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','2','Vehículo 152',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','3','Vehículo 156',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','4','Vehículo 157',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','5','Vehículo 158',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','6','Vehículo 159',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','7','Vehículo 160',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','8','Vehículo 161',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','1','Radio Tetra','9','Vehículo 162',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','1','Vehículo 151',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','10','Vehículo 163',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','11','Vehículo 164',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','2','Vehículo 152',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','3','Vehículo 156',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','4','Vehículo 157',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','5','Vehículo 158',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','6','Vehículo 159',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','7','Vehículo 160',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','8','Vehículo 161',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','2','CPU SAE','9','Vehículo 162',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','1','Vehículo 151',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','10','Vehículo 163',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','11','Vehículo 164',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','2','Vehículo 152',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','3','Vehículo 156',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','4','Vehículo 157',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','5','Vehículo 158',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','6','Vehículo 159',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','7','Vehículo 160',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','8','Vehículo 161',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','3','Consola SAE M1','9','Vehículo 162',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','1','Vehículo 151',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','10','Vehículo 163',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','11','Vehículo 164',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','2','Vehículo 152',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','3','Vehículo 156',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','4','Vehículo 157',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','5','Vehículo 158',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','6','Vehículo 159',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','7','Vehículo 160',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','8','Vehículo 161',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','4','Consola SAE M2','9','Vehículo 162',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','1','Vehículo 151',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','10','Vehículo 163',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','11','Vehículo 164',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','2','Vehículo 152',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','3','Vehículo 156',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','4','Vehículo 157',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','5','Vehículo 158',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','6','Vehículo 159',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','7','Vehículo 160',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','8','Vehículo 161',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','5','Red Wifi','9','Vehículo 162',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','1','151-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','10','156-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','11','156-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','12','156-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','13','157-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','14','157-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','15','157-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','16','157-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','17','157-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','18','157-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','19','158-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','2','151-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','20','158-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','21','158-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','22','158-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','23','158-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','24','158-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','25','159-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','26','159-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','27','159-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','28','159-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','29','159-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','3','151-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','30','159-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','31','160-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','32','160-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','33','160-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','34','160-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','35','160-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','36','160-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','37','161-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','38','161-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','39','161-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','4','151-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','40','161-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','41','161-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','42','161-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','43','162-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','44','162-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','45','162-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','46','162-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','47','162-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','48','162-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','49','163-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','5','151-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','50','163-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','51','163-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','52','163-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','53','163-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','54','163-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','55','164-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','56','164-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','57','164-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','58','164-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','59','164-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','6','151-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','60','164-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','61','152-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','62','152-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','63','152-VAL3',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','64','152-VAL4',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','65','152-VAL5',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','66','152-VAL6',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','7','156-VAL1',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','8','156-VAL2',0,0)),
    this.niveles.push(new Nivel( '1','Instalaciones Fijas','8','Equipos Embarcados','6','Validadoras','9','156-VAL3',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','1','Vehículo 151','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','10','Vehículo 163','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','11','Vehículo 164','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','2','Vehículo 152','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','3','Vehículo 156','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','4','Vehículo 157','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','5','Vehículo 158','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','6','Vehículo 159','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','7','Vehículo 160','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','8','Vehículo 161','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','1','Climatización',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','2','Iluminación Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','3','Asientos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','4','Estribos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','5','Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','6','S.I.V.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','1','Confort','7','P.M.R.',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','1','IHM',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','2','Pulsadores y Conmutadores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','3','Manipulador',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','4','Sistema de Comunicación',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','5','Asiento del Conductor',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','6','Sistemas Adicionales',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','7','Equipación de Cabina',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','2','Interfase con Conductor','8','Otros',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','1','Sistema Hombre Muerto',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','10','SAE Embarcado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','2','Sistema Lazo de Puertas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','3','Señalización Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','4','Registrador de Datos',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','5','VideoVigilancia',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','6','Sistema Telemando de Agujas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','7','Sistema de Semaforos Viarios',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','8','Sistema de Retrovisión',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','3','Control y Seguridad del Tranvía','9','Radio',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','4','Tracción','1','Equipo de Tracción',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','4','Tracción','2','ETF, UTF',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','4','Tracción','3','Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','4','Tracción','4','Equipo Refrig. Motores',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','4','Tracción','5','Resistencias de Freno',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','4','Tracción','6','Sistema de Arenado',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','5','Freno','1','Freno Hidraulico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','5','Freno','2','Freno Eléctrico',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','5','Freno','3','Freno Magnético',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','5','Freno','4','Nivel de carga',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','6','Estructura','1','Decoración Interior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','6','Estructura','2','Asideros/Barras',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','6','Estructura','3','Decoración Exterior',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','7','Bogies y Suspensiones','1','Reductora',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','7','Bogies y Suspensiones','2','Ruedas',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','7','Bogies y Suspensiones','3','Suspensiones',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','7','Bogies y Suspensiones','4','Sistema de Engrase de Pestaña',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','8','Prod. Y Distr. Energía','1','Pantografo',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','8','Prod. Y Distr. Energía','2','Disyuntor Principal',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','8','Prod. Y Distr. Energía','3','Convertidor Estático (CVS)',0,0)),
    this.niveles.push(new Nivel( '2','Material Movil','9','Vehículo 162','8','Prod. Y Distr. Energía','4','Bateria',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','1','Túnel de Lavado','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','2','Sistema de Arenado','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','3','Torno de Foso','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','4','Elevadores','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','5','Cabina de Pintura','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','6','Grúas','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','7','Plataforma Baja Bogies','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','1','Equipamiento Taller','8','Útiles y Herramientas','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','1','Sistema SAE TR',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','2','Sistema SAE TD',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','3','Control CCTV traza',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','4','Telemando Energía',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','5','Estación Base Tetra',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','6','Equipo VideoWall',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','1','Sala PCC','7','Sistema Billetaje',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','10','Climatización','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','11','Sist. Protección C. Incendios','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','12','Sist. Anti-Intrusión','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','2','Sala Servidores','1','Servidor H&K',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','2','Sala Servidores','2','Servidor TETRA',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','2','Sala Servidores','3','Servidor SAE',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','2','Sala Servidores','4','Switch CORE 1&2',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','2','Sala Servidores','5','Servidor Telefonía',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','2','Sala Servidores','6','Servidor Megafonia Paradas',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','3','Personalizador (PC+Impresora)','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','4','Red Interna Wifi','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','5','Sala Billetaje','1','Fiscalizadoras',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','6','CCTV TYC','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','7','Sist. Agua (Caliente,Fria o  Potable)','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','8','Sist. Aire Comprimido','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','2','Instalaciones','9','Sists. Eléctricos','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','1','Estructura','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','2','Cubierta','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','3','Vestuarios','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','4','Aseos','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','5','Paredes','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','6','Suelos','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','7','Carpinteria','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','3','Edificación','8','Techos','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','4','Urbanización Exterior','1','Señaliz. Horizontal','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','4','Urbanización Exterior','2','Drenage','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','4','Urbanización Exterior','3','Iluminación','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','4','Urbanización Exterior','4','Pavimentos','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','4','Urbanización Exterior','5','Arquetas','0','NULL',0,0)),
    this.niveles.push(new Nivel( '3','Talleres y Cocheras','4','Urbanización Exterior','6','Vallado','0','NULL',0,0))
    
    this.ramaunica(this.niveles)
    

    this.ramaunicae.forEach(e=>{console.log(e)})
    this.ramaunicae2.forEach((value: string, key: string) => {
      console.log(key, value);
  });

  

  }
  

 public ramaunica( niveles: Nivel[]){
   
    let i: number
    i=0
    niveles.forEach(element => { 

          if (i==0) {
           
            this.ramaunicae[i] =element.COD_RAMA
            this.ramaunicae2.set(element.COD_RAMA,element.DESC_RAMA);
                   
            i++
          } else{

            if (element.COD_RAMA != this.ramaunicae[i-1]){
              this.ramaunicae[i] =element.COD_RAMA
              this.ramaunicae2.set(element.COD_RAMA,element.DESC_RAMA);
              i++
            }
          }
    });
  
 }
 getKeys(map){
  return Array.from(map.values());
}
 


}
