export class Incidencia {
    constructor(
        public COD_INC: string,
        public COD_DETINC: string,
        public NUM_DETINC: string,
        public DESC_DETINC: string,
        public ESTADO_DETINC: string,
        public FECAP_DETINC: Date,
        public FECCI_DETINC: Date,
        public COD_RAMA_DETINC: string,
        public HORAAP_DETINC: Date,
        public HORACI_DETINC: Date,
        public COD_SISTEMA_DETINC: string,
        public COD_SUBSISTEMA_DETINC: string,
        public COD_EQUIPO_DETINC: string,
        public OBS_DETINC: string,
        public RESPUESTA_DETINC: string,
        public FECHARES_DETINC: Date,
        public HORARES_DETINC: Date,
        public SISTINOP_DETINC: boolean,
        public HORASO_DETINC: Date,
        public FECSO_DETINC: Date,
        public VALORAC_DETINC: string,
        public TIEMPOINV_DETINC: number,
        public PERSONAL_DETINC: string,
        public UTILES_DETINC: string,
        public MATERIALES_DETINC: string,
        public GARANTIA_DETINC: boolean,
        public PREVENTIVO_DETINC: boolean,
        public CORRECTIVO_DETINC: boolean,
        public OTROSVERIF_DETINC: boolean,
        public OTROSTEXT_DETINC: string,
        public VALOR_DETINC: number,
        public SEGPROP_DETINC: boolean,
        public SEGAJEN__DETINC: boolean,
        public SEGAJENTEXT__DETINC: string,
        public AVERIA_DETINC: boolean,
        public PDFPCC_DETINC: number,
        public EMAILPCC_DETINC:number,
        public UTEPCC_DETINC: number,
        public PDFMO_DETINC: boolean,
        public EMAILMO_DETINC: boolean,
        public CODLUGAR_DETINC: string,
        public CODVIA_DETINC: string,
        public COD_USUARIO: string,
        public DEP_USER: string,
        public USER_CI1: string,
        public USER_CI2: string,
        public USER_CI3: string,
        public ENUSO: boolean,
        public NOTAS_DETINC: string,
        public CONTADOR_CI: number
        
        
    ) {}

}
